# this must be provided and if not provided, it is experiment-01
run_name: experiment-01
##
run_description: "this is a demo run"
# here is my model and data
# it depends on the project
data:
  - type:
    args:
  - type:
    args:


model:
  - type:
    args:
  - type:
    args:

metric:
  - type:
    args:
  - type:
    args:

# below list all the config of runner with the default value
# you can change it if you want
optimizer:
  lr: 3e-4
scheduler:
  type: "LinearWarmupCosineLRScheduler"
  min_lr: 1e-5
  init_lr: 3e-4
  warmup_steps: 0
  warmup_start_lr: -1
training:
  epochs: 10
  print_model: true
  fp16: false
  progress_show:
    loss: false
    test_acc: true
  valid_every_n_epochs: 1
  test_every_n_epochs: 1
  progress_every_n_epochs: 1
  progress_every_n_batches: 1
  ds_config: null

log:
  log_level: "INFO"
  to_file: true
  folder: "./logs"

pt:
  pt_save: true
  pt_save_dir: "./checkpoints"
  pt_save_n_epochs: 1
  pt_best_monitor:
    loss: false
  pt_topk: 3
wandb:
  wandb_enable: false
  wandb_project_name: "default"
  wandb_offline: false
  wandb_dir: "./"
  wandb_tags: []

